/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QLabel *titulo;
    QLineEdit *cantidad;
    QLabel *ingresar;
    QPushButton *crearBoton;
    QLabel *label_2;
    QLabel *ciudaddestinoL;
    QLabel *ciudadsalidaL;
    QLineEdit *ciudadDestino;
    QLineEdit *ciudadSalida;
    QPushButton *ciudadesBoton;
    QLabel *E3;
    QLabel *RojoG4;
    QLabel *VerdeClaroG4;
    QLabel *NaranjaG4;
    QLabel *RaAZG4;
    QLabel *VCaAZG4;
    QLabel *VCaNG4;
    QLabel *NaRG4;
    QLabel *AZaNG4;
    QLabel *RaVCG4;
    QLabel *AzulG5;
    QLabel *VerdeClaroG5;
    QLabel *RojoG5;
    QLabel *NaranjaG5;
    QLabel *VCaAZG5;
    QLabel *RaAZG5;
    QLabel *VCaNG5;
    QLabel *NaRG5;
    QLabel *VerdeOscuroG5;
    QLabel *VOaRG5;
    QLabel *AZaVOG5;
    QLabel *NaVOG5;
    QLabel *VOaVCG5;
    QLabel *VerdeClaroG6;
    QLabel *AzulG6;
    QLabel *NaranjaG6;
    QLabel *RojoG6;
    QLabel *MoradoG6;
    QLabel *VerdeOscuroG6;
    QLabel *NaVCG6;
    QLabel *VOaMG6;
    QLabel *NaRG6;
    QLabel *VCaVOG6;
    QLabel *AaNG6;
    QLabel *RaAG6;
    QLabel *MaNG6;
    QLabel *RaMG6;
    QLabel *AmarilloG7;
    QLabel *LilaG7;
    QLabel *VerdeOscuroG7;
    QLabel *NaranjaG7;
    QLabel *AzulG7;
    QLabel *RojoG7;
    QLabel *MoradoG7;
    QLabel *VOaNG7;
    QLabel *NaRG7;
    QLabel *AMaVOG7;
    QLabel *LaAZG7;
    QLabel *MaAZ;
    QLabel *RaMG7;
    QLabel *AMaLG7;
    QLabel *AZaAMG7;
    QLabel *RaAZG7;
    QLabel *VOaRG7;
    QLabel *VerdeClaroG8;
    QLabel *NaranjaG8;
    QLabel *AzulG8;
    QLabel *AmarilloG8;
    QLabel *MoradoG8;
    QLabel *RojoG8;
    QLabel *LilaG8;
    QLabel *VerdeOscuroG8;
    QLabel *AMaAZG8;
    QLabel *VCaMG8;
    QLabel *AMaVCG8;
    QLabel *AZaVOG8;
    QLabel *NaAMG8;
    QLabel *RaNG8;
    QLabel *AMaRG8;
    QLabel *VOaMG8;
    QLabel *LaVOG;
    QLabel *VOaRG8;
    QLabel *VOaAMG8;
    QLabel *MaAMG8;
    QLabel *RaLG8;
    QLineEdit *TablaResultados;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(946, 678);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        titulo = new QLabel(centralwidget);
        titulo->setObjectName(QString::fromUtf8("titulo"));
        titulo->setGeometry(QRect(40, -10, 221, 101));
        QFont font;
        font.setFamily(QString::fromUtf8("Century Gothic"));
        font.setPointSize(28);
        font.setBold(true);
        font.setWeight(75);
        titulo->setFont(font);
        titulo->setWordWrap(false);
        cantidad = new QLineEdit(centralwidget);
        cantidad->setObjectName(QString::fromUtf8("cantidad"));
        cantidad->setGeometry(QRect(80, 130, 121, 31));
        cantidad->setEchoMode(QLineEdit::Password);
        ingresar = new QLabel(centralwidget);
        ingresar->setObjectName(QString::fromUtf8("ingresar"));
        ingresar->setGeometry(QRect(20, 80, 281, 41));
        ingresar->setAlignment(Qt::AlignCenter);
        crearBoton = new QPushButton(centralwidget);
        crearBoton->setObjectName(QString::fromUtf8("crearBoton"));
        crearBoton->setGeometry(QRect(80, 170, 121, 41));
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(380, 10, 501, 421));
        ciudaddestinoL = new QLabel(centralwidget);
        ciudaddestinoL->setObjectName(QString::fromUtf8("ciudaddestinoL"));
        ciudaddestinoL->setGeometry(QRect(90, 210, 101, 51));
        ciudaddestinoL->setAlignment(Qt::AlignCenter);
        ciudadsalidaL = new QLabel(centralwidget);
        ciudadsalidaL->setObjectName(QString::fromUtf8("ciudadsalidaL"));
        ciudadsalidaL->setGeometry(QRect(80, 290, 111, 41));
        ciudadsalidaL->setAlignment(Qt::AlignCenter);
        ciudadDestino = new QLineEdit(centralwidget);
        ciudadDestino->setObjectName(QString::fromUtf8("ciudadDestino"));
        ciudadDestino->setGeometry(QRect(80, 250, 121, 31));
        ciudadSalida = new QLineEdit(centralwidget);
        ciudadSalida->setObjectName(QString::fromUtf8("ciudadSalida"));
        ciudadSalida->setGeometry(QRect(80, 330, 121, 31));
        ciudadesBoton = new QPushButton(centralwidget);
        ciudadesBoton->setObjectName(QString::fromUtf8("ciudadesBoton"));
        ciudadesBoton->setGeometry(QRect(80, 380, 111, 31));
        E3 = new QLabel(centralwidget);
        E3->setObjectName(QString::fromUtf8("E3"));
        E3->setGeometry(QRect(560, 340, 71, 21));
        RojoG4 = new QLabel(centralwidget);
        RojoG4->setObjectName(QString::fromUtf8("RojoG4"));
        RojoG4->setGeometry(QRect(690, 180, 47, 13));
        VerdeClaroG4 = new QLabel(centralwidget);
        VerdeClaroG4->setObjectName(QString::fromUtf8("VerdeClaroG4"));
        VerdeClaroG4->setGeometry(QRect(360, 240, 61, 16));
        NaranjaG4 = new QLabel(centralwidget);
        NaranjaG4->setObjectName(QString::fromUtf8("NaranjaG4"));
        NaranjaG4->setGeometry(QRect(500, 60, 61, 16));
        RaAZG4 = new QLabel(centralwidget);
        RaAZG4->setObjectName(QString::fromUtf8("RaAZG4"));
        RaAZG4->setGeometry(QRect(640, 260, 47, 13));
        VCaAZG4 = new QLabel(centralwidget);
        VCaAZG4->setObjectName(QString::fromUtf8("VCaAZG4"));
        VCaAZG4->setGeometry(QRect(420, 310, 47, 13));
        VCaNG4 = new QLabel(centralwidget);
        VCaNG4->setObjectName(QString::fromUtf8("VCaNG4"));
        VCaNG4->setGeometry(QRect(380, 130, 47, 13));
        NaRG4 = new QLabel(centralwidget);
        NaRG4->setObjectName(QString::fromUtf8("NaRG4"));
        NaRG4->setGeometry(QRect(640, 110, 47, 13));
        AZaNG4 = new QLabel(centralwidget);
        AZaNG4->setObjectName(QString::fromUtf8("AZaNG4"));
        AZaNG4->setGeometry(QRect(530, 260, 47, 13));
        RaVCG4 = new QLabel(centralwidget);
        RaVCG4->setObjectName(QString::fromUtf8("RaVCG4"));
        RaVCG4->setGeometry(QRect(560, 210, 47, 13));
        AzulG5 = new QLabel(centralwidget);
        AzulG5->setObjectName(QString::fromUtf8("AzulG5"));
        AzulG5->setGeometry(QRect(590, 350, 47, 13));
        VerdeClaroG5 = new QLabel(centralwidget);
        VerdeClaroG5->setObjectName(QString::fromUtf8("VerdeClaroG5"));
        VerdeClaroG5->setGeometry(QRect(390, 210, 47, 13));
        RojoG5 = new QLabel(centralwidget);
        RojoG5->setObjectName(QString::fromUtf8("RojoG5"));
        RojoG5->setGeometry(QRect(710, 170, 47, 13));
        NaranjaG5 = new QLabel(centralwidget);
        NaranjaG5->setObjectName(QString::fromUtf8("NaranjaG5"));
        NaranjaG5->setGeometry(QRect(500, 63, 51, 20));
        VCaAZG5 = new QLabel(centralwidget);
        VCaAZG5->setObjectName(QString::fromUtf8("VCaAZG5"));
        VCaAZG5->setGeometry(QRect(440, 310, 47, 13));
        RaAZG5 = new QLabel(centralwidget);
        RaAZG5->setObjectName(QString::fromUtf8("RaAZG5"));
        RaAZG5->setGeometry(QRect(640, 250, 47, 13));
        VCaNG5 = new QLabel(centralwidget);
        VCaNG5->setObjectName(QString::fromUtf8("VCaNG5"));
        VCaNG5->setGeometry(QRect(430, 130, 47, 13));
        NaRG5 = new QLabel(centralwidget);
        NaRG5->setObjectName(QString::fromUtf8("NaRG5"));
        NaRG5->setGeometry(QRect(610, 110, 47, 13));
        VerdeOscuroG5 = new QLabel(centralwidget);
        VerdeOscuroG5->setObjectName(QString::fromUtf8("VerdeOscuroG5"));
        VerdeOscuroG5->setGeometry(QRect(530, 190, 47, 13));
        VOaRG5 = new QLabel(centralwidget);
        VOaRG5->setObjectName(QString::fromUtf8("VOaRG5"));
        VOaRG5->setGeometry(QRect(590, 170, 47, 13));
        AZaVOG5 = new QLabel(centralwidget);
        AZaVOG5->setObjectName(QString::fromUtf8("AZaVOG5"));
        AZaVOG5->setGeometry(QRect(510, 250, 47, 13));
        NaVOG5 = new QLabel(centralwidget);
        NaVOG5->setObjectName(QString::fromUtf8("NaVOG5"));
        NaVOG5->setGeometry(QRect(540, 130, 47, 13));
        VOaVCG5 = new QLabel(centralwidget);
        VOaVCG5->setObjectName(QString::fromUtf8("VOaVCG5"));
        VOaVCG5->setGeometry(QRect(460, 220, 47, 13));
        VerdeClaroG6 = new QLabel(centralwidget);
        VerdeClaroG6->setObjectName(QString::fromUtf8("VerdeClaroG6"));
        VerdeClaroG6->setGeometry(QRect(330, 200, 47, 13));
        AzulG6 = new QLabel(centralwidget);
        AzulG6->setObjectName(QString::fromUtf8("AzulG6"));
        AzulG6->setGeometry(QRect(440, 340, 47, 13));
        NaranjaG6 = new QLabel(centralwidget);
        NaranjaG6->setObjectName(QString::fromUtf8("NaranjaG6"));
        NaranjaG6->setGeometry(QRect(460, 70, 47, 13));
        RojoG6 = new QLabel(centralwidget);
        RojoG6->setObjectName(QString::fromUtf8("RojoG6"));
        RojoG6->setGeometry(QRect(690, 80, 47, 13));
        MoradoG6 = new QLabel(centralwidget);
        MoradoG6->setObjectName(QString::fromUtf8("MoradoG6"));
        MoradoG6->setGeometry(QRect(680, 340, 47, 13));
        VerdeOscuroG6 = new QLabel(centralwidget);
        VerdeOscuroG6->setObjectName(QString::fromUtf8("VerdeOscuroG6"));
        VerdeOscuroG6->setGeometry(QRect(810, 210, 47, 13));
        NaVCG6 = new QLabel(centralwidget);
        NaVCG6->setObjectName(QString::fromUtf8("NaVCG6"));
        NaVCG6->setGeometry(QRect(370, 130, 47, 13));
        VOaMG6 = new QLabel(centralwidget);
        VOaMG6->setObjectName(QString::fromUtf8("VOaMG6"));
        VOaMG6->setGeometry(QRect(750, 290, 47, 13));
        NaRG6 = new QLabel(centralwidget);
        NaRG6->setObjectName(QString::fromUtf8("NaRG6"));
        NaRG6->setGeometry(QRect(570, 60, 47, 13));
        VCaVOG6 = new QLabel(centralwidget);
        VCaVOG6->setObjectName(QString::fromUtf8("VCaVOG6"));
        VCaVOG6->setGeometry(QRect(430, 220, 47, 13));
        AaNG6 = new QLabel(centralwidget);
        AaNG6->setObjectName(QString::fromUtf8("AaNG6"));
        AaNG6->setGeometry(QRect(430, 290, 47, 13));
        RaAG6 = new QLabel(centralwidget);
        RaAG6->setObjectName(QString::fromUtf8("RaAG6"));
        RaAG6->setGeometry(QRect(520, 320, 47, 13));
        MaNG6 = new QLabel(centralwidget);
        MaNG6->setObjectName(QString::fromUtf8("MaNG6"));
        MaNG6->setGeometry(QRect(600, 320, 47, 13));
        RaMG6 = new QLabel(centralwidget);
        RaMG6->setObjectName(QString::fromUtf8("RaMG6"));
        RaMG6->setGeometry(QRect(680, 140, 47, 13));
        AmarilloG7 = new QLabel(centralwidget);
        AmarilloG7->setObjectName(QString::fromUtf8("AmarilloG7"));
        AmarilloG7->setGeometry(QRect(360, 300, 47, 13));
        LilaG7 = new QLabel(centralwidget);
        LilaG7->setObjectName(QString::fromUtf8("LilaG7"));
        LilaG7->setGeometry(QRect(450, 370, 47, 13));
        VerdeOscuroG7 = new QLabel(centralwidget);
        VerdeOscuroG7->setObjectName(QString::fromUtf8("VerdeOscuroG7"));
        VerdeOscuroG7->setGeometry(QRect(420, 100, 47, 13));
        NaranjaG7 = new QLabel(centralwidget);
        NaranjaG7->setObjectName(QString::fromUtf8("NaranjaG7"));
        NaranjaG7->setGeometry(QRect(590, 80, 47, 13));
        AzulG7 = new QLabel(centralwidget);
        AzulG7->setObjectName(QString::fromUtf8("AzulG7"));
        AzulG7->setGeometry(QRect(530, 190, 47, 13));
        RojoG7 = new QLabel(centralwidget);
        RojoG7->setObjectName(QString::fromUtf8("RojoG7"));
        RojoG7->setGeometry(QRect(730, 190, 47, 13));
        MoradoG7 = new QLabel(centralwidget);
        MoradoG7->setObjectName(QString::fromUtf8("MoradoG7"));
        MoradoG7->setGeometry(QRect(670, 340, 47, 13));
        VOaNG7 = new QLabel(centralwidget);
        VOaNG7->setObjectName(QString::fromUtf8("VOaNG7"));
        VOaNG7->setGeometry(QRect(500, 80, 47, 13));
        NaRG7 = new QLabel(centralwidget);
        NaRG7->setObjectName(QString::fromUtf8("NaRG7"));
        NaRG7->setGeometry(QRect(660, 120, 47, 13));
        AMaVOG7 = new QLabel(centralwidget);
        AMaVOG7->setObjectName(QString::fromUtf8("AMaVOG7"));
        AMaVOG7->setGeometry(QRect(350, 190, 47, 13));
        LaAZG7 = new QLabel(centralwidget);
        LaAZG7->setObjectName(QString::fromUtf8("LaAZG7"));
        LaAZG7->setGeometry(QRect(480, 270, 47, 13));
        MaAZ = new QLabel(centralwidget);
        MaAZ->setObjectName(QString::fromUtf8("MaAZ"));
        MaAZ->setGeometry(QRect(600, 290, 47, 13));
        RaMG7 = new QLabel(centralwidget);
        RaMG7->setObjectName(QString::fromUtf8("RaMG7"));
        RaMG7->setGeometry(QRect(710, 260, 47, 13));
        AMaLG7 = new QLabel(centralwidget);
        AMaLG7->setObjectName(QString::fromUtf8("AMaLG7"));
        AMaLG7->setGeometry(QRect(390, 340, 47, 13));
        AZaAMG7 = new QLabel(centralwidget);
        AZaAMG7->setObjectName(QString::fromUtf8("AZaAMG7"));
        AZaAMG7->setGeometry(QRect(410, 230, 47, 13));
        RaAZG7 = new QLabel(centralwidget);
        RaAZG7->setObjectName(QString::fromUtf8("RaAZG7"));
        RaAZG7->setGeometry(QRect(610, 210, 47, 13));
        VOaRG7 = new QLabel(centralwidget);
        VOaRG7->setObjectName(QString::fromUtf8("VOaRG7"));
        VOaRG7->setGeometry(QRect(520, 150, 47, 13));
        VerdeClaroG8 = new QLabel(centralwidget);
        VerdeClaroG8->setObjectName(QString::fromUtf8("VerdeClaroG8"));
        VerdeClaroG8->setGeometry(QRect(360, 200, 47, 13));
        NaranjaG8 = new QLabel(centralwidget);
        NaranjaG8->setObjectName(QString::fromUtf8("NaranjaG8"));
        NaranjaG8->setGeometry(QRect(460, 90, 47, 13));
        AzulG8 = new QLabel(centralwidget);
        AzulG8->setObjectName(QString::fromUtf8("AzulG8"));
        AzulG8->setGeometry(QRect(440, 340, 47, 13));
        AmarilloG8 = new QLabel(centralwidget);
        AmarilloG8->setObjectName(QString::fromUtf8("AmarilloG8"));
        AmarilloG8->setGeometry(QRect(540, 210, 47, 13));
        MoradoG8 = new QLabel(centralwidget);
        MoradoG8->setObjectName(QString::fromUtf8("MoradoG8"));
        MoradoG8->setGeometry(QRect(630, 340, 47, 13));
        RojoG8 = new QLabel(centralwidget);
        RojoG8->setObjectName(QString::fromUtf8("RojoG8"));
        RojoG8->setGeometry(QRect(620, 90, 47, 13));
        LilaG8 = new QLabel(centralwidget);
        LilaG8->setObjectName(QString::fromUtf8("LilaG8"));
        LilaG8->setGeometry(QRect(750, 90, 47, 13));
        VerdeOscuroG8 = new QLabel(centralwidget);
        VerdeOscuroG8->setObjectName(QString::fromUtf8("VerdeOscuroG8"));
        VerdeOscuroG8->setGeometry(QRect(760, 230, 47, 13));
        AMaAZG8 = new QLabel(centralwidget);
        AMaAZG8->setObjectName(QString::fromUtf8("AMaAZG8"));
        AMaAZG8->setGeometry(QRect(450, 290, 47, 13));
        VCaMG8 = new QLabel(centralwidget);
        VCaMG8->setObjectName(QString::fromUtf8("VCaMG8"));
        VCaMG8->setGeometry(QRect(410, 240, 47, 13));
        AMaVCG8 = new QLabel(centralwidget);
        AMaVCG8->setObjectName(QString::fromUtf8("AMaVCG8"));
        AMaVCG8->setGeometry(QRect(440, 190, 47, 13));
        AZaVOG8 = new QLabel(centralwidget);
        AZaVOG8->setObjectName(QString::fromUtf8("AZaVOG8"));
        AZaVOG8->setGeometry(QRect(510, 320, 47, 13));
        NaAMG8 = new QLabel(centralwidget);
        NaAMG8->setObjectName(QString::fromUtf8("NaAMG8"));
        NaAMG8->setGeometry(QRect(460, 140, 47, 13));
        RaNG8 = new QLabel(centralwidget);
        RaNG8->setObjectName(QString::fromUtf8("RaNG8"));
        RaNG8->setGeometry(QRect(540, 70, 47, 13));
        AMaRG8 = new QLabel(centralwidget);
        AMaRG8->setObjectName(QString::fromUtf8("AMaRG8"));
        AMaRG8->setGeometry(QRect(570, 140, 47, 13));
        VOaMG8 = new QLabel(centralwidget);
        VOaMG8->setObjectName(QString::fromUtf8("VOaMG8"));
        VOaMG8->setGeometry(QRect(720, 300, 47, 13));
        LaVOG = new QLabel(centralwidget);
        LaVOG->setObjectName(QString::fromUtf8("LaVOG"));
        LaVOG->setGeometry(QRect(780, 150, 47, 13));
        VOaRG8 = new QLabel(centralwidget);
        VOaRG8->setObjectName(QString::fromUtf8("VOaRG8"));
        VOaRG8->setGeometry(QRect(680, 140, 47, 13));
        VOaAMG8 = new QLabel(centralwidget);
        VOaAMG8->setObjectName(QString::fromUtf8("VOaAMG8"));
        VOaAMG8->setGeometry(QRect(670, 200, 47, 13));
        MaAMG8 = new QLabel(centralwidget);
        MaAMG8->setObjectName(QString::fromUtf8("MaAMG8"));
        MaAMG8->setGeometry(QRect(570, 240, 47, 13));
        RaLG8 = new QLabel(centralwidget);
        RaLG8->setObjectName(QString::fromUtf8("RaLG8"));
        RaLG8->setGeometry(QRect(660, 60, 47, 13));
        TablaResultados = new QLineEdit(centralwidget);
        TablaResultados->setObjectName(QString::fromUtf8("TablaResultados"));
        TablaResultados->setGeometry(QRect(510, 350, 311, 71));
        MainWindow->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "RentACar", nullptr));
        titulo->setText(QCoreApplication::translate("MainWindow", "RENT A CAR", nullptr));
        cantidad->setText(QString());
        ingresar->setText(QCoreApplication::translate("MainWindow", "Ingresar la cantidad de vertices que desea en el grafo\n"
"(Se permite de 7 a 15 vertices) ", nullptr));
        crearBoton->setText(QCoreApplication::translate("MainWindow", "Crear Grafo", nullptr));
        label_2->setText(QString());
        ciudaddestinoL->setText(QCoreApplication::translate("MainWindow", "Ciudad de Destino", nullptr));
        ciudadsalidaL->setText(QCoreApplication::translate("MainWindow", "Ciudad de Salida", nullptr));
        ciudadDestino->setText(QString());
        ciudadesBoton->setText(QCoreApplication::translate("MainWindow", "Registrar Ciudades", nullptr));
        E3->setText(QString());
        RojoG4->setText(QString());
        VerdeClaroG4->setText(QString());
        NaranjaG4->setText(QString());
        RaAZG4->setText(QString());
        VCaAZG4->setText(QString());
        VCaNG4->setText(QString());
        NaRG4->setText(QString());
        AZaNG4->setText(QString());
        RaVCG4->setText(QString());
        AzulG5->setText(QString());
        VerdeClaroG5->setText(QString());
        RojoG5->setText(QString());
        NaranjaG5->setText(QString());
        VCaAZG5->setText(QString());
        RaAZG5->setText(QString());
        VCaNG5->setText(QString());
        NaRG5->setText(QString());
        VerdeOscuroG5->setText(QString());
        VOaRG5->setText(QString());
        AZaVOG5->setText(QString());
        NaVOG5->setText(QString());
        VOaVCG5->setText(QString());
        VerdeClaroG6->setText(QString());
        AzulG6->setText(QString());
        NaranjaG6->setText(QString());
        RojoG6->setText(QString());
        MoradoG6->setText(QString());
        VerdeOscuroG6->setText(QString());
        NaVCG6->setText(QString());
        VOaMG6->setText(QString());
        NaRG6->setText(QString());
        VCaVOG6->setText(QString());
        AaNG6->setText(QString());
        RaAG6->setText(QString());
        MaNG6->setText(QString());
        RaMG6->setText(QString());
        AmarilloG7->setText(QString());
        LilaG7->setText(QString());
        VerdeOscuroG7->setText(QString());
        NaranjaG7->setText(QString());
        AzulG7->setText(QString());
        RojoG7->setText(QString());
        MoradoG7->setText(QString());
        VOaNG7->setText(QString());
        NaRG7->setText(QString());
        AMaVOG7->setText(QString());
        LaAZG7->setText(QString());
        MaAZ->setText(QString());
        RaMG7->setText(QString());
        AMaLG7->setText(QString());
        AZaAMG7->setText(QString());
        RaAZG7->setText(QString());
        VOaRG7->setText(QString());
        VerdeClaroG8->setText(QString());
        NaranjaG8->setText(QString());
        AzulG8->setText(QString());
        AmarilloG8->setText(QString());
        MoradoG8->setText(QString());
        RojoG8->setText(QString());
        LilaG8->setText(QString());
        VerdeOscuroG8->setText(QString());
        AMaAZG8->setText(QString());
        VCaMG8->setText(QString());
        AMaVCG8->setText(QString());
        AZaVOG8->setText(QString());
        NaAMG8->setText(QString());
        RaNG8->setText(QString());
        AMaRG8->setText(QString());
        VOaMG8->setText(QString());
        LaVOG->setText(QString());
        VOaRG8->setText(QString());
        VOaAMG8->setText(QString());
        MaAMG8->setText(QString());
        RaLG8->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
